import PublicationControls from "../features/creator/PublicationControls";
import Button from "../components/ui/Button";
import Field from "../components/ui/Field";
import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import KitchenShell from "../components/KitchenShell";
import RecipeImage from "../components/RecipeImage";
import { useKitchen, useKitchenResource } from "../utils/useKitchen";
import { safeAccent } from "../utils/kitchen";
import { sourceLink } from "../utils/sunny";

function recipeIdFromInput(value, origin = window.location.origin) {
  const input = value.trim();
  const id = /^[0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12}$/i;
  if (id.test(input)) return input;
  try {
    const url = new URL(input, origin);
    const match = url.pathname.match(/^\/recipes\/([^/]+)\/?$/);
    return url.origin === origin && !url.username && !url.password && match && id.test(match[1]) ? match[1] : null;
  } catch { return null; }
}

function CreatorContent() {
  const { data, mutate, busy, canEdit, isOwner, setError } = useKitchen();
  const catalog = useKitchenResource("/workspace/catalog");
  const [branding, setBranding] = useState({ name: "", accentColor: "#FED369", description: "", version: 0 });
  const [brandingDirty, setBrandingDirty] = useState(false);
  const [permission, setPermission] = useState({ recipeId: "", permissionNote: "", sourceUrl: "", permissionConfirmed: false });
  const [swap, setSwap] = useState({ fromIngredient: "", toIngredient: "", ratio: "", note: "", sourceUrl: "", reviewed: false });
  const [previewForm, setPreviewForm] = useState({ recipeId: "", swapId: "", servings: "2" });
  const [preview, setPreview] = useState(null);
  const [previewReviewed, setPreviewReviewed] = useState(false);
  const approvedSwaps = useMemo(() => (data.substitutions || []).filter(item => item.approvalStatus === 'approved'), [data.substitutions]);
  useEffect(() => { setPreview(null); setPreviewReviewed(false); if (previewForm.swapId && !approvedSwaps.some(item => item.id === previewForm.swapId)) setPreviewForm(current => ({...current, swapId: ''})); }, [approvedSwaps, previewForm.swapId]);
  useEffect(() => { if (data.workspace && !brandingDirty) setBranding({ name: data.workspace.name || "", accentColor: safeAccent(data.workspace.accentColor), description: data.workspace.description || "", version: data.workspace.version }); }, [data.workspace, brandingDirty]);
  const saveBranding = async event => { event.preventDefault(); if (await mutate("Save workspace branding", "/workspace", branding)) setBrandingDirty(false); };
  const addCatalog = async event => {
    event.preventDefault();
    if (!permission.permissionConfirmed || !sourceLink(permission.sourceUrl)) { setError("Confirm permission and add a valid source link."); return; }
    const recipeId = recipeIdFromInput(permission.recipeId);
    if (!recipeId) { setError("Paste a LetMeCook recipe link or a valid recipe ID."); return; }
    if (await mutate("Add permission-declared recipe", "/workspace/catalog", { ...permission, recipeId, permissionNote: permission.permissionNote.trim() })) setPermission({ recipeId: "", permissionNote: "", sourceUrl: "", permissionConfirmed: false });
  };
  const addSwap = async event => { event.preventDefault(); if (!swap.reviewed || !sourceLink(swap.sourceUrl)) { setError("Review the swap and add a valid source link."); return; } if (await mutate("Save reviewed substitution", "/substitutions", { ...swap, ratio: Number(swap.ratio), fromIngredient: swap.fromIngredient.trim(), toIngredient: swap.toIngredient.trim() })) setSwap({ fromIngredient: "", toIngredient: "", ratio: "", note: "", sourceUrl: "", reviewed: false }); };
  const previewSwap = async event => {
    event.preventDefault();
    if (!approvedSwaps.some(item => item.id === previewForm.swapId)) { setError("Choose an approved swap."); return; }
    const recipeId = recipeIdFromInput(previewForm.recipeId);
    if (!recipeId) { setError("Paste a LetMeCook recipe link or a valid recipe ID."); return; }
    const response = await mutate("Preview substitution quantities", "/substitutions/preview", { recipeId, swapId: previewForm.swapId, servings: Number(previewForm.servings) }, undefined, false);
    if (response) { setPreview(response); setPreviewReviewed(false); }
  };
  return <>
    <nav className="kitchen-section-links" aria-label="Creator sections"><a href="#creator-catalog">Collection</a><a href="#creator-workspace">Workspace</a><a href="#creator-substitutions">Swaps</a><a href="#creator-preview">Preview</a></nav>
    <div className="kitchen-workspace kitchen-creator-workspace"><div className="kitchen-task-main">
      <section className="kitchen-panel" id="creator-catalog"><h2>Recipe collection</h2><p>Add recipes you have permission to use. Permissions are recorded, not independently verified.</p>{isOwner && <details className="kitchen-disclosure kitchen-disclosure-secondary"><summary>Add a recipe with permission</summary><form onSubmit={addCatalog}><fieldset disabled={!!busy}><div className="kitchen-form-grid"><Field>Recipe link or ID<input required value={permission.recipeId} maxLength="2000" onChange={event => setPermission({ ...permission, recipeId: event.target.value })} placeholder="Paste a LetMeCook recipe link" /></Field><Field>Source link<input type="url" required value={permission.sourceUrl} onChange={event => setPermission({ ...permission, sourceUrl: event.target.value })} /></Field></div><Field>Permission or license<textarea required maxLength="2000" rows="2" value={permission.permissionNote} onChange={event => setPermission({ ...permission, permissionNote: event.target.value })} placeholder="Describe how you have permission to use this recipe" /></Field><Field className="kitchen-checkbox"><input type="checkbox" required checked={permission.permissionConfirmed} onChange={event => setPermission({ ...permission, permissionConfirmed: event.target.checked })} />I have permission to add this recipe.</Field><Button className="kitchen-primary" type="submit" disabled={!permission.permissionConfirmed}>Add recipe</Button></fieldset></form></details>}
      {catalog.loading ? <p role="status">Loading recipes…</p> : catalog.error ? <div className="kitchen-error"><p>{catalog.error}</p><Button className="kitchen-secondary" type="button" onClick={catalog.reload}>Reload recipes</Button></div> : catalog.data?.recipes?.length ? <div className="kitchen-recipe-grid">{catalog.data.recipes.map(recipe => <article className="kitchen-recipe-card" key={recipe.id}><Link to={`/recipes/${recipe.recipeId}`}>{recipe.imageUrl && <RecipeImage src={recipe.imageUrl} alt={recipe.title} loading="lazy" />}<h3>{recipe.title}</h3></Link><p className="kitchen-help">{recipe.permissionNote}</p>{sourceLink(recipe.sourceUrl) && <a className="kitchen-text-link" href={sourceLink(recipe.sourceUrl)} target="_blank" rel="noreferrer">Source ↗</a>}{isOwner && <Button className="kitchen-text-button kitchen-danger" type="button" disabled={!!busy} onClick={() => mutate("Remove catalog record", `/workspace/catalog/${recipe.id}`, undefined, "DELETE")}>Remove from collection</Button>}</article>)}</div> : <p className="kitchen-empty-small">Your collection is empty. Add a recipe above.</p>}
    </section>
    </div><aside className="kitchen-context" aria-label="Workspace management">
      <section className="kitchen-panel" id="creator-workspace"><div className="kitchen-panel-heading"><div><h2>{data.workspace?.name || "Your workspace"}</h2>{data.workspace?.description && <p>{data.workspace.description}</p>}</div><span className="kitchen-badge">{isOwner ? "Owner" : "Member"}</span></div>
      {isOwner && <details className="kitchen-disclosure kitchen-disclosure-secondary"><summary>Edit workspace</summary><form className="kitchen-workspace-form" onSubmit={saveBranding}><fieldset disabled={!!busy}><Field>Workspace name<input required maxLength="100" value={branding.name} onChange={event => { setBrandingDirty(true); setBranding({ ...branding, name: event.target.value }); }} /></Field><Field>Accent color<input type="color" value={safeAccent(branding.accentColor)} onChange={event => { setBrandingDirty(true); setBranding({ ...branding, accentColor: event.target.value }); }} /></Field><Field>Description<textarea rows="3" maxLength="1000" value={branding.description} onChange={event => { setBrandingDirty(true); setBranding({ ...branding, description: event.target.value }); }} /></Field><Button className="kitchen-primary" type="submit">Save workspace</Button></fieldset></form></details>}
      <details className="kitchen-disclosure kitchen-disclosure-secondary"><summary>Preview private collection</summary><p className="kitchen-help">Visible only in this kitchen. This does not publish a website.</p><div className="kitchen-brand-preview" style={{ borderTopColor: safeAccent(data.workspace?.accentColor) }}><h3>{data.workspace?.name || "Your recipe workspace"}</h3>{data.workspace?.description && <p>{data.workspace.description}</p>}{catalog.loading ? <p role="status">Loading recipes…</p> : catalog.error ? <div className="kitchen-error"><p>{catalog.error}</p><Button className="kitchen-secondary" type="button" onClick={catalog.reload}>Reload recipes</Button></div> : catalog.data?.recipes?.length ? <><div className="kitchen-private-preview-grid">{catalog.data.recipes.slice(0, 4).map(recipe => <Link key={recipe.id} to={`/recipes/${recipe.recipeId}`}>{recipe.imageUrl && <RecipeImage src={recipe.imageUrl} alt={recipe.title} loading="lazy" />}<strong>{recipe.title}</strong></Link>)}</div><a className="kitchen-text-link" href="#creator-catalog">View collection ({catalog.data.recipes.length})</a></> : <p className="kitchen-empty-small">Add a recipe to preview your collection.</p>}</div></details>
    <PublicationControls />
    </section>
    </aside></div>
    <section className="kitchen-panel" id="creator-substitutions"><h2>Ingredient swaps</h2><p>Submit swaps for review before previewing. Approval is not an allergy-safety guarantee or expert certification.</p>{canEdit && <details className="kitchen-disclosure kitchen-disclosure-secondary"><summary>Submit a swap</summary><form onSubmit={addSwap}><fieldset disabled={!!busy}><div className="kitchen-form-grid"><Field>Replace ingredient<input required maxLength="100" value={swap.fromIngredient} onChange={event => setSwap({ ...swap, fromIngredient: event.target.value })} /></Field><Field>With ingredient<input required maxLength="100" value={swap.toIngredient} onChange={event => setSwap({ ...swap, toIngredient: event.target.value })} /></Field><Field>Amount ratio<input type="number" min="0.000001" step="any" required value={swap.ratio} onChange={event => setSwap({ ...swap, ratio: event.target.value })} /></Field><Field>Supporting source link<input type="url" required value={swap.sourceUrl} onChange={event => setSwap({ ...swap, sourceUrl: event.target.value })} /></Field></div><Field>How should it be used?<textarea required maxLength="2000" rows="2" value={swap.note} onChange={event => setSwap({ ...swap, note: event.target.value })} /></Field><Field className="kitchen-checkbox"><input type="checkbox" required checked={swap.reviewed} onChange={event => setSwap({ ...swap, reviewed: event.target.checked })} />I reviewed this swap and its source.</Field><Button className="kitchen-primary" type="submit" disabled={!swap.reviewed}>Submit for review</Button></fieldset></form></details>}
      <ul className="kitchen-simple-list">{(data.substitutions || []).map(item => <li key={item.id}><div><h3>{item.fromIngredient} → {item.toIngredient}</h3><p>Ratio: {item.ratio} · {item.note}</p><span className="kitchen-badge">{item.approvalStatus === 'approved' ? 'Approved for preview' : item.approvalStatus === 'rejected' ? 'Review rejected' : 'Awaiting review'}</span>{item.approvalNote && <p className="kitchen-help">Review note: {item.approvalNote}</p>}{sourceLink(item.approvalSourceUrl) && <a className="kitchen-text-link" href={sourceLink(item.approvalSourceUrl)} target="_blank" rel="noreferrer">Reviewer’s source ↗</a>}<small>Submitted{item.reviewedBy ? ` by ${item.reviewedBy}` : ""}{item.reviewedAt ? ` · ${new Date(item.reviewedAt).toLocaleDateString("en")}` : ""}</small>{sourceLink(item.sourceUrl) && <a className="kitchen-text-link" href={sourceLink(item.sourceUrl)} target="_blank" rel="noreferrer">Supporting source ↗</a>}</div>{canEdit && <Button type="button" className="kitchen-text-button" disabled={!!busy} onClick={() => mutate("Remove reviewed substitution", `/substitutions/${item.id}`, undefined, "DELETE")}>Remove</Button>}</li>)}</ul>{!data.substitutions?.length && <p className="kitchen-empty-small">No swaps yet. Submit one for review.</p>}</section>
    <section className="kitchen-panel" id="creator-preview"><h2>Preview an approved swap</h2><p>Compare ingredients for your servings. The source recipe stays unchanged.</p><form onSubmit={previewSwap}><fieldset disabled={!!busy || !approvedSwaps.length}><div className="kitchen-form-grid"><Field>Recipe link or ID<input required maxLength="2000" value={previewForm.recipeId} onChange={event => { setPreview(null); setPreviewForm({ ...previewForm, recipeId: event.target.value }); }} placeholder="Paste a LetMeCook recipe link" /></Field><Field>Approved swap<select required value={previewForm.swapId} onChange={event => { setPreview(null); setPreviewForm({ ...previewForm, swapId: event.target.value }); }}><option value="">Choose an approved swap</option>{approvedSwaps.map(item => <option key={item.id} value={item.id}>{item.fromIngredient} → {item.toIngredient} · {item.ratio}</option>)}</select></Field><Field>Servings<input type="number" min="1" max="12" step="1" required value={previewForm.servings} onChange={event => { setPreview(null); setPreviewForm({ ...previewForm, servings: event.target.value }); }} /></Field></div><Button className="kitchen-primary" type="submit">Preview changes</Button></fieldset></form>{!approvedSwaps.length && <p className="kitchen-empty-small">Submit a swap above. It must be approved before preview.</p>}{preview && <div className="kitchen-swap-preview"><h3>{preview.supported ? "Ingredient preview" : "This swap is not supported"}</h3>{preview.warnings?.map((warning, index) => <p className="kitchen-note" key={index}>{warning}</p>)}{!!preview.changed?.length && <ul className="kitchen-simple-list">{preview.changed.map((item, index) => <li key={index}><span><strong>{item.fromIngredient} → {item.toIngredient}</strong><small>{item.quantity === null ? "Quantity requires review" : `${item.quantity} ${item.unit || ""}`}</small></span></li>)}</ul>}{preview.supported && <><div className="kitchen-table-wrap"><table><thead><tr><th>Ingredient after review</th><th>Quantity</th></tr></thead><tbody>{preview.ingredients?.map((item, index) => <tr key={index}><td>{item.name || item.ingredient}</td><td>{item.quantity ?? "Unknown"} {item.unit}</td></tr>)}</tbody></table></div><p className="kitchen-note">Check ingredients and cooking instructions before using this swap. Approval does not guarantee safety.</p><Field className="kitchen-checkbox"><input type="checkbox" checked={previewReviewed} onChange={event => setPreviewReviewed(event.target.checked)} />I checked these changes. The source instructions are unchanged.</Field>{previewReviewed && <Link className="kitchen-text-link" to={`/recipes/${preview.sourceRecipeId}`}>Compare with original recipe</Link>}</>}</div>}</section>
  </>;
}

export default function Creator() { return <KitchenShell title="Creator workspace" intro="Manage recipes and reviewed swaps for your kitchen."><CreatorContent /></KitchenShell>; }
