# syntax=docker/dockerfile:1
FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /build
COPY server/pom.xml ./pom.xml
RUN --mount=type=cache,id=letmecook-maven21,target=/root/.m2,sharing=locked \
    mvn -B dependency:go-offline
COPY server/src ./src
RUN --mount=type=cache,id=letmecook-maven21,target=/root/.m2,sharing=locked \
    mvn -B package

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build --chown=1005:1005 /build/target/letMeCook-0.0.1-SNAPSHOT.jar /app/app.jar
USER 1005:1005
ENV HOME=/tmp
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
