export const kitchenGuides = [
  {
    id: 'guide-sunny',
    title: 'Find a meal with Sunny',
    description: 'A craving, a few ingredients or a photo is enough to start.',
    steps: [
      'Describe your ingredients, time and foods to leave out. Choose Find my recipes.',
      'For a photo, check the ingredient names and choose Use these ingredients before searching.',
      'Answer A quick check if Sunny needs a detail. Open Why this recipe? to see the match, then choose View recipe.',
    ],
    appLink: { path: '/sunny', label: 'Find dinner with Sunny' },
    feature: { path: '/features#discover', label: 'Explore dinner inspiration' },
  },
  {
    id: 'guide-pantry',
    title: 'Bring your pantry into the plan',
    description: 'Keep the ingredients you have close to your next dinner decision.',
    steps: [
      'Open Pantry and use Add stock, or choose Add from a photo.',
      'Check names, amounts and units. Leave an amount blank if you do not know it; add your own Use by date.',
      'For a photo, review the entries and choose Add confirmed stock. Under What can I cook?, choose Find matching recipes.',
    ],
    appLink: { path: '/pantry', label: 'Open your pantry' },
    feature: { path: '/features#shop', label: 'Explore pantry-aware shopping' },
  },
  {
    id: 'guide-plan',
    title: 'Plan dinners and adjust portions',
    description: 'Start with one dinner, three dinners or a full week.',
    steps: [
      'In Plan preferences, choose Dinners, Servings per dinner and Maximum cooking time.',
      'Describe your tastes and exclusions, then choose Plan my week. Turn on saved preferences when you want them included.',
      'Change Servings per dinner and choose Update servings to recalculate groceries. For faster meals, use Preview tighter time before applying.',
      'Review the draft and choose Save plan & list when signed in.',
    ],
    appLink: { path: '/meal-planner', label: 'Plan your dinners' },
    feature: { path: '/features#plan', label: 'Explore flexible meal plans' },
  },
  {
    id: 'guide-groceries',
    title: 'Take one list to the store',
    description: 'Keep the meals you choose and the ingredients to buy together.',
    steps: [
      'Create a dinner plan and review Groceries. Turn on Use my pantry to check what is already at home.',
      'Check marked amounts and portions, then use Copy list or Download. Check off what you have or bought.',
      'To share the list, choose Prepare kitchen list, review what it replaces and choose Confirm publish.',
      'Open kitchen shopping to use the saved checklist. For a budget, record pack prices in Pantry first.',
    ],
    appLink: { path: '/meal-planner', label: 'Build your grocery list' },
    feature: { path: '/features#shop', label: 'Explore shopping tools' },
  },
  {
    id: 'guide-cook',
    title: 'Listen, time and keep your place',
    description: 'Choose when Sunny speaks and when you move to the next step.',
    steps: [
      'Open a recipe and choose Cook along. Choose Step by step to hear and replay an individual instruction, or Timed flow to read each step after the wait you set.',
      'Set minutes and seconds, then choose Start timer. Keep the page open with sound on for reminders; acknowledge a finished timer.',
      'For a spoken question, choose Record a question, allow microphone access, then Stop & transcribe. Check the words before choosing Ask Sunny.',
      'For Timed flow, review the minutes and seconds for each step before starting. Reading finishes before the wait begins; pause or stop whenever you need. In Step by step, choose Done, next step yourself.',
    ],
    appLink: { path: '/recipes', label: 'Choose a recipe to cook' },
    feature: { path: '/features#cook', label: 'Explore cooking guidance' },
  },
  {
    id: 'guide-after-cooking',
    title: 'Remember the taste, save the leftovers',
    description: 'Let a good meal help shape another dinner.',
    steps: [
      'At the end of Cook along, check the stock amounts you used and choose Confirm cooked meal.',
      'Open How did it taste?, add your rating and preferences, then choose Save my feedback. Keep allergies in your profile.',
      'Open Save leftovers, enter the portions and dates you checked, then choose Save confirmed leftovers.',
      'Manage prepared portions in Pantry. In the planner, choose Reuse my confirmed leftovers; record eaten portions back in Pantry.',
    ],
    appLink: { path: '/pantry', label: 'Manage your pantry and leftovers' },
    feature: { path: '/features#your-kitchen', label: 'Explore your personal kitchen' },
  },
  {
    id: 'guide-household',
    title: 'Bring your household together',
    description: 'Share a kitchen while each person keeps control of their preferences.',
    steps: [
      'Open Household and use Create household, or Accept invitation with the code you received.',
      'When invitations are enabled, the owner uses Create invite code and shares it with the new member.',
      'Each member can open My preference sharing and choose Share my preferences or Revoke my sharing.',
      'In the planner, choose Kitchen for this plan and Include shared household preferences to include members who opted in.',
    ],
    appLink: { path: '/household', label: 'Open your household kitchen' },
    feature: { path: '/features#your-kitchen', label: 'Explore household cooking' },
  },
  {
    id: 'guide-recipes',
    title: 'Keep recipes you want to make again',
    description: 'Build a collection around meals you enjoy and recipes of your own.',
    steps: [
      'When signed in, open a recipe and choose Save recipe to add it to Favorites.',
      'In Favorites, use Manage favorites to remove a recipe, then choose Done managing.',
      'For a recipe of your own, open My recipes, choose Create recipe and complete the ingredients and method before Save recipe.',
    ],
    appLink: { path: '/user-recipe', label: 'Open my recipes' },
    feature: { path: '/features#your-kitchen', label: 'Explore recipe collections' },
  },
];
