export const startingPoints = [
  { id: 'dinner', group: 'Find a meal', label: 'Find something to cook tonight', title: 'Start with what sounds good.', description: 'Tell Sunny about your ingredients, time and foods to leave out.', steps: ['Write a dinner request or choose an example.', 'Review the search conditions and choose a recipe.'], path: '/sunny', cta: 'Find dinner with Sunny', guide: 'guide-sunny' },
  { id: 'photo', group: 'Find a meal', label: 'Cook from an ingredient photo', title: 'Turn what you see into dinner ideas.', description: 'Use a photo as a starting point, then check the ingredients yourself.', steps: ['Upload a photo and correct the ingredient names.', 'Choose Use these ingredients before searching.'], path: '/sunny', cta: 'Start with a photo', guide: 'guide-sunny' },
  { id: 'preferences', group: 'Find a meal', label: 'Make suggestions more personal', title: 'Bring your tastes into the kitchen.', description: 'Keep your food preferences together and give feedback after a meal.', steps: ['Update your cuisines, preferences and ingredients to leave out.', 'Use saved preferences when planning; record how a cooked meal tasted.'], path: '/edit-profile', cta: 'Edit my food preferences', guide: 'guide-after-cooking', account: true },
  { id: 'week', group: 'Plan and shop', label: 'Plan dinners for the week', title: 'Give your week a dinner rhythm.', description: 'Choose one, three or seven dinners around your time and portions.', steps: ['Set the dinners, servings and time you have.', 'Review meals and groceries before saving the plan.'], path: '/meal-planner', cta: 'Plan my dinners', guide: 'guide-plan' },
  { id: 'groceries', group: 'Plan and shop', label: 'Make a grocery list', title: 'Bring one clear list to the store.', description: 'Gather the ingredients for your plan and check what is already at home.', steps: ['Review the plan’s grocery amounts and your pantry.', 'Copy or download the list, or publish it to your selected kitchen.'], path: '/meal-planner', cta: 'Build my grocery list', guide: 'guide-groceries' },
  { id: 'budget', group: 'Plan and shop', label: 'Plan with my grocery budget', title: 'Put your own prices into the plan.', description: 'Record pack prices so the planner can check the ingredients it can price.', steps: ['Add observed pack prices and units in Pantry.', 'Choose a budget in the planner and review any amounts or prices still missing.'], path: '/pantry', cta: 'Add my grocery prices', guide: 'guide-groceries', account: true },
  { id: 'pantry', group: 'Use what you have', label: 'Cook with pantry ingredients', title: 'Check the kitchen before choosing dinner.', description: 'Keep stock names, amounts and dates editable, then find meals around them.', steps: ['Add stock or review ingredients from a photo.', 'Choose ingredients to use and find matching recipes.'], path: '/pantry', cta: 'Open my pantry', guide: 'guide-pantry', account: true },
  { id: 'leftovers', group: 'Use what you have', label: 'Use prepared leftovers', title: 'Give a good meal another turn.', description: 'Keep confirmed prepared portions separate from your ingredient stock.', steps: ['Save leftover portions and dates after cooking.', 'Choose Reuse my confirmed leftovers when making another plan.'], path: '/pantry', cta: 'Manage my leftovers', guide: 'guide-after-cooking', account: true },
  { id: 'cook', group: 'Cook and share', label: 'Follow a recipe with voice and timers', title: 'Keep your place while dinner cooks.', description: 'Listen one step at a time or follow a timed reading flow.', steps: ['Choose a recipe and open Cook along.', 'Choose Step by step, or review the waits and start Timed flow.'], path: '/recipes', cta: 'Choose a recipe to cook', guide: 'guide-cook' },
  { id: 'household', group: 'Cook and share', label: 'Plan with my household', title: 'Bring everyone into one kitchen.', description: 'Share stock and shopping tasks; each member chooses whether to share preferences.', steps: ['Create or join a household kitchen.', 'Select it in the planner and include preferences from members who opted in.'], path: '/household', cta: 'Open my household kitchen', guide: 'guide-household', account: true },
  { id: 'favorites', group: 'Cook and share', label: 'Return to my favorite recipes', title: 'Keep the meals you want to make again.', description: 'Save recipes you like and build a collection that feels like you.', steps: ['Choose Save recipe on a recipe page.', 'Open Favorites when you need a familiar dinner idea.'], path: '/favourites', cta: 'Open my favorites', guide: 'guide-recipes', account: true },
  { id: 'recipes', group: 'Cook and share', label: 'Add a recipe of my own', title: 'Make room for your own cooking.', description: 'Keep your recipes alongside the meals you enjoy discovering.', steps: ['Open My recipes and choose Create recipe.', 'Add ingredients and the method, then save your recipe.'], path: '/user-recipe', cta: 'Open my recipes', guide: 'guide-recipes', account: true },
];
